### ISSUE TITLE
Switch to flip to blacklist

### ISSUE THREAD

**Issue by ryanmasuga** [JasonEtco/craft-emailwhitelist#1]
Nice plugin. Would be more useful to us if the list were a blacklist, though. Perhaps adding a switch to flip to tell the plugin which logic to use?

**Comment by JasonEtco** [comment]
I agree, but I'd probably add a second table, that way you can have a whitelist and a blacklist at the same time.

**Comment by ryanmasuga** [comment]
Even better! In our case, a client can have all sorts of domains allowed to register, but we noticed some mail.ru domains sneaking in. We'd like to blacklist that domain, and any others we find that aren't legit.

**Comment by JasonEtco** [comment]
I actually ended up adding the toggle, an extra list would have been redundant. Good suggestion @masuga!
