### ISSUE TITLE
Allow for bulk/large lists - one domain per line

### ISSUE THREAD

**Issue by ryanmasuga** [JasonEtco/craft-emailwhitelist#2]
The current domain field is nice if one has a small number of potential domains. But if you wanted to add a large list, such as this large common domain blacklist: http://www.joewein.de/sw/blacklist.htm it would be impossible. I'd personally like to see one domain per line in a text field. Would make blocking/adding 100's of domains very easy.

**Comment by JasonEtco** [comment]
I hear you; that was actually a real question for me. It's a much simpler, clearer decision to have the current table but you're totally right that it's a pain for bulk adding. I think a better solution would be to have a "Bulk Add" feature, that takes a text field and then plunks the result into the table.

If you're dealing with 100s of domains, it would be a pain to remove a lot of them in the table though; not sure what the best solution is here.
